version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_project
    ports:
      - "8080:80"
    volumes:
      - mydata:/usr/share/nginx/html   # attach named volume

volumes:
  mydata: